### ISSUE TITLE
New page for complete purchase

### ISSUE THREAD

**Issue by samzih** [samzih/tech-store#29]
> Knappen för att slutföra köpet skall, vid klickning, visa en bekräftelse på köpet i en popup.

When a user clicks on the "Slutför ditt köp" button on the shopping cart page a popup/modal should show up in the center of the screen that tells the user their purchase has gone through and is complete.

### **Here are some visual examples/references:**

**Functionality:**
![simple-button-to-popup-modal-window](https://user-images.githubusercontent.com/114141910/197394936-7455ca33-2a92-40ff-b454-81c2354e2c42.gif)

**How the popup/modal layout should sort of look like:**
![payment-success-page-template-html-7](https://user-images.githubusercontent.com/114141910/197395282-f05ab74c-4401-4748-853b-e950299a73e4.png)

**Some more inspiration/refs:**
![bd169d67331ccc9edd92c39dca770921](https://user-images.githubusercontent.com/114141910/197395187-0b743ee7-5125-4b25-b60f-ee7daf8543b8.png)
![checkout](https://user-images.githubusercontent.com/114141910/197395007-3c0fd50e-2c6c-41da-8286-c2630b328238.png)
![1_JPNPtq18htkC2ISoHuh-rQ](https://user-images.githubusercontent.com/114141910/197395026-73f4741f-0f06-4290-83a6-2bcb8d8b8e70.png)
![purchase-thanks_600x208](https://user-images.githubusercontent.com/114141910/197395059-5a8b5733-b3a4-44ef-a3af-e3ffc2208920.png)
![Magento_order_approval_rectangle_1_Illustrative_Banner_Blog](https://user-images.githubusercontent.com/114141910/197395111-7bc3c354-1118-4852-815c-1c442a831815.jpg)
![07-Thankyou-Page](https://user-images.githubusercontent.com/114141910/197395124-c31560f4-2c11-492a-821d-bb3e4c68c239.png)
![thank-you-page-sample-1](https://user-images.githubusercontent.com/114141910/197395134-6c7d65f0-3386-4e6a-b609-585464db2d68.png)

**Comment by elinrobertson** [comment]
Har gjort en del av stylingen på popupen men är långt ifrån klar. Fastnat.
Försökt mig på JS-delen men lyckas inte få till det

**Comment by elinrobertson** [comment]
Istället för att göra en popup vid slutför köp så gör vi istället en ny sida som en "bekräftelse"
