### ISSUE TITLE
Remove product(s) from local storage cart with "Ta bort" button

### ISSUE THREAD

**Issue by samzih** [samzih/tech-store#30]
> Varje produkt i listan skall visa bilden, titeln, priset **och en knapp för att ta bort produkten ur kundvagnen.**

When a user clicks on the "Ta bort" button for a specific product it should be removed from the local storage cart key & then the function to re-render the products in the cart should be called.
![ApplicationFrameHost_aIq2qPGAXJ](https://user-images.githubusercontent.com/114141910/197400294-f6114dbf-7016-4f45-b2b4-3745403598b8.png)

**Comment by sabest2022** [comment]
I have fixed the code but do you think that we should remove the object also?1

**Comment by samzih** [comment]
I don't think we should be using the filter and the if else statement, it seems overly confusing. 

I'm going to give it a try and see if I can fix this using the solution I talked about before during the meeting.

**Comment by sabest2022** [comment]
I did not understand what you mean by we should not using filter! the code have to work properly and you should explain why you think it does not work properly!

**Comment by samzih** [comment]
I was able to get it completely functional but with much simpler code (6 lines). No if else statement and using the `splice()` method instead of filter.

They both achieve the same result so far (I believe), one is just less code & cleaner than the other.

**Comment by sabest2022** [comment]
Sure, but I did not understand how you count the lines! I have written 9 lines and your code is 15 lines! There is also a bug with your code which is not in the other one.
